### PR TITLE
Feature/ws gptable method

### PR DESCRIPTION
**Pull request by foster999**
Method not yet implemented

I'm stuck on trying to get our Workbook class to use our Worksheet class over the XlsxWriter class
related to #18

### CODE REVIEW

**Comment by foster999** [comment]
Error when creating worksheet:
`_add_sheet() received unexpected kwarg "worksheet_class"`
Can't find a reference to this "worksheet_class" arg anywhere

**Comment by foster999** [comment]
Hey @alexander-newton, could you take a look at my implementation of `write_gptable()` in GPWorksheet please?

I'm planning to use a `_write_element` function for each element of the GPTable. This returns the position to continue writing from - so that the elements that are used define the spacing between each other.

**Comment by foster999** [comment]
Considering this now, most elements will be written identically. Only differences will be:

- Table, will need writing cell-wise. Might want additional spacing around it
- Units, should be associated with the appropriate columns
- Scope, should hang to the top right of the table

All others are written to the left edge and will move the position to the next row

**Comment by foster999** [comment]
Have added three methods accordingly:

- `_write_element()` for title and source
-  `_write_element_list()` for subtitles, legend and notes
-  `_write_table_elements()` for scope, units and table (all at once)

**Comment by alexander-newton** [comment]
I'll have a look tomorrow.

**Pull request merged**
